In [1]:
3 + 2 * 5 # using Python as a calculator

13

In [2]:
weight_kg = 60 # assigning a value to a variable
print(weight_kg)

60


In [4]:
print("weight in pounds:", weight_kg * 2.2) # printing

weight in pounds: 132.0


In [5]:
weight_kg = 65 # re-assigning a variable
print("weight in pounds:", weight_kg * 2.2)

weight in pounds: 143.0


In [6]:
var_1, var_2 = "Grace", "Hopper" # multiple assignment
print("var_1 is:", var_1)
print("var_2 is:", var_2)

var_1 is: Grace
var_2 is: Hopper


In [10]:
import numpy # loading data with numpy
our_data = numpy.loadtxt(fname="data/inflammation-01.csv", delimiter=",")
print(our_data)

[[0. 0. 1. ... 3. 0. 0.]
 [0. 1. 2. ... 1. 0. 1.]
 [0. 1. 1. ... 2. 1. 1.]
 ...
 [0. 1. 1. ... 1. 1. 1.]
 [0. 0. 0. ... 0. 2. 0.]
 [0. 0. 1. ... 1. 1. 0.]]


In [12]:
print(type(our_data)) # type (Python) vs .dtype (numpy)
print(our_data.dtype)

<class 'numpy.ndarray'>
float64


In [13]:
print(our_data.shape)

(60, 40)


In [16]:
first_value = our_data[0, 0] # numpy array indexing
another_value = our_data[30, 20]
print(first_value, another_value)

0.0 13.0


In [17]:
print(our_data[0:4, 0:10]) # numpy array slicing

[[0. 0. 1. 3. 1. 2. 4. 7. 8. 3.]
 [0. 1. 2. 1. 2. 1. 3. 2. 2. 6.]
 [0. 1. 1. 3. 3. 2. 6. 2. 5. 9.]
 [0. 0. 2. 0. 4. 2. 2. 1. 6. 7.]]


In [20]:
print(our_data[:4, :10]) # more numpy array slicing
print(our_data[50:, 30:])

[[0. 0. 1. 3. 1. 2. 4. 7. 8. 3.]
 [0. 1. 2. 1. 2. 1. 3. 2. 2. 6.]
 [0. 1. 1. 3. 3. 2. 6. 2. 5. 9.]
 [0. 0. 2. 0. 4. 2. 2. 1. 6. 7.]]
[[ 7.  9.  3.  3.  6.  3.  4.  1.  2.  0.]
 [ 8.  5.  4.  1.  3.  2.  1.  3.  1.  0.]
 [10.  8.  7.  5.  2.  2.  4.  1.  2.  1.]
 [ 7.  6.  5.  4.  1.  4.  2.  2.  2.  1.]
 [ 4.  5.  5.  2.  2.  5.  1.  0.  0.  1.]
 [ 3.  5.  3.  5.  4.  5.  3.  3.  0.  1.]
 [ 7.  7.  5.  6.  3.  4.  2.  2.  1.  1.]
 [ 8.  6.  6.  4.  3.  5.  2.  1.  1.  1.]
 [10.  8.  8.  6.  5.  5.  2.  0.  2.  0.]
 [ 8.  5.  3.  5.  4.  1.  3.  1.  1.  0.]]


In [25]:
print(numpy.mean(our_data)) # all patients, all days
print(numpy.mean(our_data[0])) # patient 1, all days

6.14875
5.45


In [26]:
print(our_data.shape, our_data[0].shape) # 2D array vs. 1D array

(60, 40) (40,)


In [22]:
import time
print(time.ctime()) # getting the current system time

Thu Jan 23 15:13:40 2020


In [23]:
# more multiple assignment
maxval, minval, stdval = numpy.max(our_data), numpy.min(our_data), numpy.std(our_data)